FROM saltstack-bootstrap-new-node
USER root

RUN apt-get install -y iputils-ping

RUN curl https://raw.githubusercontent.com/alanrossx2/SaltStack-Bootstrap/master/bootstrap-node.sh | bash -s -- -n salt_minion -i 10.1.1.1
